=== xswzaq44321/Sysmaker_Simulator/workspace/json-schemas/datapack.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "description": "This schema defines standard datapack format.",
    "properties": {
        "pins": {
            "type": "array",
            "description": "",
            "items": {
                "type": "string",
                "description": ""
            },
            "minProperties": 1
        },
        "beginTime": {
            "type": "string",
            "pattern": "^\\d+\\s*ns$",
            "description": "begin time in nanosecond"
        },
        "endTime": {
            "type": "string",
            "pattern": "^\\d+\\s*ns$",
            "description": "end time in nanosecond"
        },
        "type": {
            "type": "string",
            "description": "",
            "examples": [ "GPIO", "UART", "SPI" ]
        },
        "Interface Configuration": {
            "type": "object",
            "description": "interface configuration",
            "properties": {
                "Pin Configuration": {
                    "type": "object",
                    "description": "dictionary of pins to it's function",
                    "minItems": 1,
                    "patternProperties": {
                        "^P\\w+$": {
                            "type": [
                                "string",
                                "null"
                            ],
                            "description": "function of this pin, can be null",
                            "title": "pin number"
                        }
                    },
                    "additionalProperties": false
                }
            },
            "required": [
                "Pin Configuration"
            ],
            "additionalProperties": {
                "description": "addons"
            }
        },
        "Data": {
            "type": "object",
            "description": "pin data",
            "properties": {
                "PinStates": {
                    "type": "object",
                    "description": "map of pin's name to pin value, in voltage",
                    "patternProperties": {
                        "^P\\w+$": {
                            "type": "string",
                            "description": "pin name to it's voltage level"
                        }
                    },
                    "additionalProperties": false
                }
            },
            "required": [ "PinStates" ],
            "additionalProperties": {
                "description": "addons"
            }
        }
    },
    "required": [ "pins", "type", "Interface Configuration", "Data" ]
}

=== xswzaq44321/Sysmaker_Simulator/workspace/stubs/fake_qemu/datapack_SPI.json
{
    "pins": [
        "PE2",
        "PE5",
        "PE6",
        "PG0",
        "PG1"
    ],
    "beginTime": "30ns",
    "type": "SPI",
    "Interface Configuration": {
        "Pin Configuration": {
            "PE2": "SCLK",
            "PE5": "MISO",
            "PE6": "MOSI"
        },
        "Clock Frequency": 4000000,
        "SPI Mode": 3,
        "Bit Order": "MSB",
        "Data Size": 8
    },
    "Data": {
        "PinStates": {
            "PG0": "0V",
            "PG1": "5V"
        },
        "MOSI": [ 187, 0, 0, 0 ],
        "MISO": [ ]
    }
}

=== xswzaq44321/Sysmaker_Simulator/workspace/stubs/fake_qemu/datapack_UART.json
{
    "pins": [
        "PB2",
        "PB3"
    ],
    "beginTime": "10ns",
    "type": "UART",
    "Interface Configuration": {
        "Pin Configuration": {
            "PB2": "TX",
            "PB3": "RX"
        },
        "Baud Rate": 9600,
        "Data Bits": 8,
        "Parity Bit": 0,
        "Stop Bits": 1
    },
    "Data": {
        "PinStates": { },
        "TX": [ 104, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100 ],
        "RX": [ ]
    }
}
